
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.prueba.parser;

/** CUP generated class containing symbol constants. */
public class SimpleParserSym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DECIMAL = 3;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int TIMES = 8;
  public static final int LPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "DECIMAL",
  "LPAREN",
  "RPAREN",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIV"
  };
}

